### ISSUE TITLE
This guy is SCAMMER!!

### ISSUE THREAD

**Issue by Dyrindyi** [Kelvin-1013/Solana-Arbitrage-Bot-rust-multi-dex-cross-swap-program#13]
This guy written that main program is in private and when I contacted him he asked $2K for it. I asked for the DEMO or proof of his product which he could not provide it. 
This guy do no have any product. He is a scammer. Do not pay any single penny to him!!!

**Comment by Kelvin-1013** [comment]
NO I am not.
He is scammer.
https://drive.google.com/file/d/1egJ9rjetABlJVVmQyvMUXV4UTcQNNRl5/view?usp=drive_link

**Comment by Dyrindyi** [comment]
The video you showing is a simple Volume Bot coded in Typescript and available in Github for free. Just search "Solana Volume Bot" in Github. This is no way related to your "Solana-Arbitrage-Bot-rust-multi-dex-cross-swap-program" which you claim coded in RUST. You do not know even ABCD of RUST programming. You are just a SCAMMER who try to scam people by showing fake video of a open source volume bot. I request all user to report this Scammer to Github to BAN him and avoid other to get scammed.
