### ISSUE TITLE
This guy is SCAMMER!!!

### ISSUE THREAD

**Issue by Dyrindyi** [Kelvin-1013/Solana-Arbitrage-Bot-rust-multi-dex-cross-swap-program#14]
This GUY is a SCAMMER!!! He will ask for $2K for a bot which never exist. He will just show a simple volume bot coded in Typescript and available for Free on GITHUB. Stay away from this SCAMMER!!!

**Comment by Kelvin-1013** [comment]
Ok , I am a scammer
